# Generated by Django 3.0.8 on 2022-02-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('phone_no', models.IntegerField()),
                ('city', models.CharField(max_length=400)),
                ('area_address', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('date_of_order', models.DateTimeField(verbose_name='date ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carparts.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('model_no', models.IntegerField()),
                ('variant', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unit_price', models.IntegerField()),
                ('quantity_stock', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carparts.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carparts.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carparts.Product')),
            ],
        ),
    ]
